name: proyecto-devops
services:
   proyecto-devops:
      image: localhost:8082/proyecto-devops
      restart: always
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=development
      secrets:
