services:
  proyecto-devops:
    image: localhost:8082/proyecto-devops
    restart: always
    ports:
      - "3000:3000"
    environment:
      - AMBIENTE=development
#       - API_KEY=/run/secrets/api-key
#     secrets:
#       - api-key
# secrets:
#   api-key:
#     file: api_key.txt
