services:
   proyecto-devops:
      image: localhost:8082/proyecto-devops
      restart: always
      ports:
        - "3000:3000"
      environment:
        - AMBIENTE=development
        - API_KEY=/run/secrets/api_key
      secrets:
        - api_key
    secrets:
      api_key: api_key.txt
