name: proyecto-devops
services:
  mi-proyecto-devops-tarea-3:
    image: localhost:8082/mi-proyecto-devops-tarea-3
    restart: always
    ports:
      - "3000:3000"
    environment:
      - AMBIENTE=development
    volumes:
    - /tmp/ficheros-contenedor:/var/ficheros
