pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker { image 'node:20.11.1-alpine3.19' }
            }
            stages {
                stage('checkout') {
                    steps {
                        echo "hola mundo"
                    }

                }
            }
        }
         stage('crear imagen docker') {
            steps {
                script {
                    docker.withRegistry('http://localhost:8082', 'nexus-key') {
                        sh 'docker build -t localhost:8082/mi-proyecto-devops-tarea-3 .'
                        sh "docker tag localhost:8082/mi-proyecto-devops-tarea-3 localhost:8082/mi-proyecto-devops-tarea-3:${env.BRANCH_NAME}-${env.BUILD_NUMBER}"
                        sh 'docker push localhost:8082/mi-proyecto-devops-tarea-3'
                        sh "docker push localhost:8082/mi-proyecto-devops-tarea-3:${env.BRANCH_NAME}-${env.BUILD_NUMBER}"
                    }
                }
            }
        }
    }
}
