pipeline {
    agent any
    stages {
        stage('node pipeline') {
            stages {
                stage('checkout') {
                    steps {
                        echo "hola mundo"
                    }

                }
            }
        }
    }
}
